### ISSUE TITLE
Current state?

### ISSUE THREAD

**Issue by jadbox** [leelynne/sqserv#1]
How far off is this from being ready to use?

**Comment by leelynne** [comment]
Hey thanks for the inquiry!  It's definitely production ready I just need to add documentation.  My company has used it in production for awhile now with both very low and fairly high throughput queues (~200/sec).  So far I have found reusing the http handler abstraction to work really well.  It allows reuse of any kind of http middleware you want.

The only thing I want to fix is there is currently no throttling of ingest from SQS.  So if your messaging processing takes longer than it does to pull from SQS the library builds an internal 'queue' of running go routines.  

I'll add documentation and examples this weekend.

**Comment by leelynne** [comment]
Documentation and examples added.  

Tagged as the v1.0.0 release
